### ISSUE TITLE
Overriding every button background to transparent

### ISSUE THREAD

**Issue by tomyda** [steven-tey/novel#135]
Buttons look like this with the `<Editor />` imported.
<img width="463" alt="image" src="https://github.com/steven-tey/novel/assets/54825937/7957969a-be8e-40d4-92e9-1f657ef89e74">
And like this with the `<Editor />`  commented:
<img width="484" alt="image" src="https://github.com/steven-tey/novel/assets/54825937/d1719619-8e88-47e7-9b79-d286e9e433df">
The theme change occurs when the component is mounted.
My Stack is Next with Chakra UI.

This property seems to be the problem:
<img width="430" alt="image" src="https://github.com/steven-tey/novel/assets/54825937/6f4f4964-d951-42bd-af3e-ed193032ede1">

**Comment by krehak** [comment]
The same happens with Mantine UI

**Comment by MarkLyck** [comment]
shadCN gets overwritten as well.

**Comment by steven-tey** [comment]
Sorry for the delay here! This should be fixed in `novel@0.1.22`: https://github.com/steven-tey/novel/releases/tag/0.1.22

**Comment by tomyda** [comment]
<img width="1343" alt="image" src="https://github.com/steven-tey/novel/assets/54825937/b0776e8f-bcdf-41b5-ac9f-d32f3e0807a3">
@steven-tey still happening on chakraUI :(
