### ISSUE TITLE
CSS conflict with shadcn ui's button style

### ISSUE THREAD

**Issue by timtbdev** [steven-tey/novel#143]
There's a css style sheet conflict with shadcn ui's button. Shadcn UI's button is hidden everywhere, and it changes it's absolute position.

**Comment by jaqnjilai** [comment]
fyi, i downgraded to 0.1.17 for now to fix this issue

**Comment by steven-tey** [comment]
Sorry for the delay here! This should be fixed in `novel@0.1.22`: https://github.com/steven-tey/novel/releases/tag/0.1.22

**Comment by JungRama** [comment]
Hi, its seems the issue are still there when using shadcn. The button should be white but its seems the color is gone

![image](https://github.com/steven-tey/novel/assets/31382668/7a5a052a-aaba-4c89-bb3e-f9e39501ed37)
